/**
 * The Bible screen is Bible Strong's reader (the fork in strong/, served at /app/strong). Its chapter
 * links name a book by its OSIS id in lower case (/bible/kjv/john/3/16); this maps the app's book
 * slugs to them, the KJV Apocrypha in 1611 order as the feed numbers them.
 */
const OSIS: Record<string, string> = {
  "genesis": "gen",
  "exodus": "exod",
  "leviticus": "lev",
  "numbers": "num",
  "deuteronomy": "deut",
  "joshua": "josh",
  "judges": "judg",
  "ruth": "ruth",
  "1-samuel": "1sam",
  "2-samuel": "2sam",
  "1-kings": "1kgs",
  "2-kings": "2kgs",
  "1-chronicles": "1chr",
  "2-chronicles": "2chr",
  "ezra": "ezra",
  "nehemiah": "neh",
  "esther": "esth",
  "job": "job",
  "psalms": "ps",
  "proverbs": "prov",
  "ecclesiastes": "eccl",
  "song-of-solomon": "song",
  "isaiah": "isa",
  "jeremiah": "jer",
  "lamentations": "lam",
  "ezekiel": "ezek",
  "daniel": "dan",
  "hosea": "hos",
  "joel": "joel",
  "amos": "amos",
  "obadiah": "obad",
  "jonah": "jonah",
  "micah": "mic",
  "nahum": "nah",
  "habakkuk": "hab",
  "zephaniah": "zeph",
  "haggai": "hag",
  "zechariah": "zech",
  "malachi": "mal",
  "matthew": "matt",
  "mark": "mark",
  "luke": "luke",
  "john": "john",
  "acts": "acts",
  "romans": "rom",
  "1-corinthians": "1cor",
  "2-corinthians": "2cor",
  "galatians": "gal",
  "ephesians": "eph",
  "philippians": "phil",
  "colossians": "col",
  "1-thessalonians": "1thess",
  "2-thessalonians": "2thess",
  "1-timothy": "1tim",
  "2-timothy": "2tim",
  "titus": "titus",
  "philemon": "phlm",
  "hebrews": "heb",
  "james": "jas",
  "1-peter": "1pet",
  "2-peter": "2pet",
  "1-john": "1john",
  "2-john": "2john",
  "3-john": "3john",
  "jude": "jude",
  "revelation": "rev",
  "1-esdras": "1esd",
  "2-esdras": "2esd",
  "tobit": "tob",
  "judith": "jdt",
  "esther-greek": "addesth",
  "wisdom-of-solomon": "wis",
  "sirach": "sir",
  "baruch": "bar",
  "epistle-of-jeremiah": "epjer",
  "song-of-the-three-children": "prazar",
  "susanna": "sus",
  "bel-and-the-dragon": "bel",
  "prayer-of-manasseh": "prman",
  "1-maccabees": "1macc",
  "2-maccabees": "2macc",
};

const STRONG_BASE = "/app/strong";

/** The reader's address for a book, chapter and optional verses ("16" or "16-18"). */
export function strongReaderPath(slug?: string, chapter?: number, verses?: string | null): string {
  const book = slug ? OSIS[slug] : undefined;
  if (!book || !chapter) return `${STRONG_BASE}/`;
  const passage = verses && /^\d+(-\d+)?$/.test(verses) ? `/${verses}` : "";
  return `${STRONG_BASE}/bible/kjv/${book}/${chapter}${passage}`;
}
