/** CI integration against real generated bytes; no network or remote R2 writes. */
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import worker from '../src/index.ts';
import { signInitData } from '../src/initdata.mjs';
import { sha256 } from '../../shared/resources.ts';
import type { Env } from '../src/env.ts';
const output = process.argv[2];
if (!output) throw new Error('Pass a built artifact directory');
const inventory = JSON.parse(await readFile(path.join(output, 'inventory.json'), 'utf8'));
const catalog = JSON.parse(await readFile(path.join(output, 'catalog.json'), 'utf8'));
const files = new Map<string, string>(inventory.objects.map((o: { key: string; file: string }) => [o.key, path.join(output, o.file)]));
const writes = new Map<string, Uint8Array>(); let reads = 0;
const object = async (key: string) => {
  const bytes = writes.get(key) ?? (files.has(key) ? new Uint8Array(await readFile(files.get(key)!)) : undefined);
  if (!bytes) return null;
  const etag = await sha256(bytes);
  return { size: bytes.length, etag, httpEtag: `"${etag}"`, arrayBuffer: async () => bytes.buffer, json: async () => JSON.parse(new TextDecoder().decode(bytes)) };
};
const bucket = {
  get: async (key: string) => { reads++; return object(key); },
  put: async (key: string, data: string | Uint8Array, opts?: { onlyIf?: { etagDoesNotMatch?: string; etagMatches?: string } }) => {
    const current = await object(key), guard = opts?.onlyIf;
    if (current && guard?.etagDoesNotMatch === '*' || guard?.etagMatches && current?.etag !== guard.etagMatches) return null;
    writes.set(key, typeof data === 'string' ? new TextEncoder().encode(data) : data); return object(key);
  },
};
const env = { AUDIO: bucket, BOT_TOKEN: 'resource-artifact-test', ADMIN_IDS: '42' } as unknown as Env;
const init = await signInitData({ auth_date: String(Math.floor(Date.now() / 1000)), user: { id: 42, first_name: 'Test' } }, env.BOT_TOKEN);
const start = performance.now();
const publish = await worker.fetch(new Request('https://example.invalid/api/resources/catalog', { method: 'PUT', headers: { authorization: `tma ${init}`, 'if-match': '*', 'content-type': 'application/json' }, body: JSON.stringify(catalog) }), env);
assert.equal(publish.status, 200, await publish.clone().text());
assert.ok(reads < 400, `Publication used ${reads} reads`);
console.log(`Published all four real bundles in process: ${reads} R2 reads, ${Math.round(performance.now() - start)}ms.`);
for (const e of catalog.resources) {
  reads = 0;
  const key = e.id === 'strongs' ? 'entry/H430' : 'book';
  const response = await worker.fetch(new Request(`https://example.invalid/api/resources/${e.id}/${e.release}/record?key=${key}`), env);
  assert.equal(response.status, 200); assert.equal((await response.json() as { release: string }).release, e.release);
  assert.equal(reads, 4, 'Current record read needs catalog, manifest, bucket and one data shard');
}
console.log('Pinned record lookups succeeded for all four resources. No remote writes.');
