import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router';
import type { z } from 'zod';
import { Relationships, type PersonEdit } from '@shared/cms-people';
import type { CmsChange } from '@shared/cms';
import { Sheet } from '@/bible/ui/Sheet';
import { api } from './client';
import { Field, Group } from './fields';
type Choice={id:string;name:string};
type Source={id:string;name:string;sha:string;value:z.infer<typeof PersonEdit>;people:Choice[]};
export function PeopleList(){const[search,setSearch]=useState('');const q=useQuery({queryKey:['cms','people'],queryFn:()=>api<{people:Choice[]}>('/api/admin/cms/people')});return <><h2>People</h2><Field label="Find a person" value={search} onChange={setSearch}/>{q.isError?<p role="alert">{q.error.message}</p>:null}<div className="cms-list">{q.data?.people.filter(p=>`${p.name} ${p.id}`.toLowerCase().includes(search.toLowerCase())).slice(0,100).map(p=><Link key={p.id} to={p.id}><b>{p.name}</b><small>{p.id}</small></Link>)}</div></>;}
export function PeopleEditor(){const{id=''}=useParams();const q=useQuery({queryKey:['cms','person',id],queryFn:()=>api<Source>(`/api/admin/cms/people/${encodeURIComponent(id)}`),refetchOnWindowFocus:false,refetchOnReconnect:false});if(q.isPending)return <p>Loading person…</p>;if(q.isError)return <p role="alert">{q.error.message}</p>;return <PersonForm key={q.data.sha} source={q.data}/>;}
function Relation({label,selected,choices,onChange}:{label:string;selected:string[];choices:Choice[];onChange:(ids:string[])=>void}){const[search,setSearch]=useState('');return <Group title={label}><div className="cms-list">{selected.map(id=><div key={id}><span>{choices.find(p=>p.id===id)?.name??id}<small>{id}</small></span><button type="button" onClick={()=>onChange(selected.filter(v=>v!==id))}>Remove</button></div>)}</div><Field label={`Find ${label.toLowerCase()}`} value={search} onChange={setSearch}/>{search.length>1?<div className="cms-list">{choices.filter(p=>!selected.includes(p.id)&&`${p.name} ${p.id}`.toLowerCase().includes(search.toLowerCase())).slice(0,20).map(p=><button key={p.id} type="button" onClick={()=>{onChange([...selected,p.id]);setSearch('');}}>{p.name} · {p.id}</button>)}</div>:null}</Group>;}
function PersonForm({source}:{source:Source}){const[value,setValue]=useState(source.value),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate();const save=async()=>{setBusy(true);setError('');try{const c=await api<CmsChange>('/api/admin/cms/people',{method:'POST',body:JSON.stringify({id:source.id,sha:source.sha,value,reason})});navigate(`/settings/admin/changes/${c.id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};return <Sheet open title="Edit person" subTitle={source.name} height="full" onClose={()=>navigate('/settings/admin/people')} footer={<div className="cms-actions"><button className="btn" disabled={busy||reason.trim().length<3} onClick={()=>void save()}>{busy?'Saving…':'Save for review'}</button></div>}><div className="cms-form"><Field label="Summary" multiline value={value.description} onChange={description=>setValue({...value,description})}/><p>Relationship changes update the matching link on the other person’s profile in the same review. Existing unresolved source ids are preserved until you correct them.</p>{Relationships.map(k=><Relation key={k} label={k[0].toUpperCase()+k.slice(1)} selected={value[k]} choices={source.people.filter(p=>p.id!==source.id)} onChange={v=>setValue({...value,[k]:v})}/>)}<Group title="Picture">{value.image?<>{(['src','caption','credit','license','sourceUrl']as const).map(k=><Field key={k} label={`Picture ${k}`} value={value.image![k]} onChange={v=>setValue({...value,image:{...value.image!,[k]:v}})}/>)}<button type="button" onClick={()=>setValue({...value,image:null})}>Remove picture</button></>:<button type="button" onClick={()=>setValue({...value,image:{src:'',caption:'',credit:'',license:'',sourceUrl:''}})}>Add picture</button>}</Group><Field label="Reason for this change" multiline value={reason} onChange={setReason}/>{error?<p role="alert">{error}</p>:null}</div></Sheet>;}
